spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: develop
    password: JFKL2kljf$@2(nici23
    url: jdbc:mysql://10.19.16.3:50008/springboot?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
